### ISSUE TITLE
Data Connection Speed Indicator 

### ISSUE THREAD

**Issue by kskarthik** [mozilla-b2g/gecko-tablet#33]
As a user i want to see the web  while tablet is connected to internet 

Connection speed Mb/s in status bar

**Comment by kskarthik** [comment]
@benfrancis what's your opinion about this ?

**Comment by benfrancis** [comment]
Hi @kskarthik,

The feature description doesn't really make any sense, but I think you're asking for the network connection speed to be shown in the status bar.

It's really too early to be taking feature requests for this project because we're currently just testing the core product concept in a user study. But my opinion about this feature is that it would compromise the simplicity of the UI and should therefore either be an optional setting you can turn on, or an add-on. 

Also, it would require a reliable way to measure network speed. In Firefox OS you can see the WiFi connection speed in network settings, but the WiFi connection speed is not indicative of the Internet connection speed.

Let's re-visit this if the project gets past its initial user study!

Ben

**Comment by kskarthik** [comment]
okay
