### ISSUE TITLE
Web Notifications

### ISSUE THREAD

**Issue by Coder206** [mozilla-b2g/gecko-tablet#48]
Harnessing the power of Web Notifications would be a great addition to the status bar, pull down and see your notifications from Facebook and other sites.

**Comment by benfrancis** [comment]
I agree, I also think this should include support for Push Notifications using Service Workers so that you can receive notifications even when a web app isn't open.

_"As a user I want to be able to choose to receive notifications from websites/web apps when something changes so that I can be kept up to date."_

We'd need to think about the UI design. In general I've tried to avoid hard to discover gestures in favour of interactions with clear visual affordances as I think it's more appropriate for our target audience for this project. Perhaps something as simple as tapping a notifications area in the status bar could work.
