### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by Coder206** [mozilla-b2g/gecko-tablet#52]
Support the File System API to allow the tablet to save downloads.

**Comment by Coder206** [comment]
Also, this would permit interactions with external storage devices

**Comment by benfrancis** [comment]
As I understand it the W3C File System API only creates a sandbox for websites to store files in, it doesn't give you access to the full file system or external storage devices.

For a production product we would need a way to save downloaded files like Chrome OS does. I suspect the UI may be backed by a local web service (potentially WebDAV) rather than a DOM API though.

**Comment by Coder206** [comment]
@benfrancis Oh ok, that sounds good! So this project is still supported by Mozilla unlike FxOS?

**Comment by benfrancis** [comment]
B2G OS is an ongoing Mozilla open source project. Mozilla is not working on any more Firefox OS branded smartphone products but we are still working on Smart TVs and exploring other product opportunities through a Product Innovation Process.

Project Tablet is a proposal as part of that process to build a tablet dedicated to browsing the web https://wiki.mozilla.org/Connected_Devices/Projects/Project_Tablet

Currently we are just carrying out a user study to validate the concept with a simple prototype, so proposing advanced features may not be the best way to contribute at this point. We will need help in circulating a questionnaire though!

**Comment by Coder206** [comment]
@benfrancis I understand. I am just really excited about this! I would be happy to circulate a questionnaire for you.

**Comment by benfrancis** [comment]
@Coder206 Thank you for your enthusiasm! Please see [here](https://discourse.mozilla-community.org/t/help-needed-tablet-survey/9581) for the survey.
